#!/bin/bash

source "${XDG_CONFIG_HOME}/bspwm/theme.sh"

"${XDG_CONFIG_HOME}"/bspwm/scripts/workspaces.sh

dunst &
sxhkd &
picom -b 
setxkbmap -model pc105 -layout us,ru -option grp:alt_shift_toggle
nitrogen --restore &
udiskie &
eww daemon
launch-polybar bspwm

bspc config window_gap           4
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config border_width "3px"
bspc config border_radius 8
bspc config normal_border_color  "${BACKGROUND_COLOR}"
bspc config focused_border_color "${ACCENT_COLOR}"

#bspc rule -a appname desktop='^N' args=values
bspc rule -a 'Steam' focus=off
bspc rule -a 'Friends List' state=floating focus=off
bspc rule -a 'Steam - News' state=floating focus=off
bspc rule -a Zathura state=tiled
bspc rule -a Gsimplecal state=floating center=on follow=on
# bspc rule -a Eww state=floating
bspc rule -a Eww state=floating focus=off sticky=on border=off
