#!/usr/bin/env sh

[ -f  "${XDG_CONFIG_HOME}/shell/theme.sh" ] \
    && . "${XDG_CONFIG_HOME}/shell/theme.sh"

[ -f "${XDG_CONFIG_HOME}"/bspwm/scripts/workspaces.sh ] \
    && . "${XDG_CONFIG_HOME}"/bspwm/scripts/workspaces.sh

picom -b
xrdb -load "${XDG_CONFIG_HOME}/X11/Xresources"
sxhkd "${XDG_CONFIG_HOME}/sxhkd/sxhkdrc-bspwm" &
launch-polybar bspwm
wallpapers-ctrl load

bspc config window_gap           4
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config border_width "3px"
bspc config border_radius 8
bspc config normal_border_color  "${BACKGROUND_COLOR}"
bspc config focused_border_color "${PRIMARY_COLOR}"

#bspc rule -a appname desktop='^N' args=values
bspc rule -a 'Steam' focus=off
bspc rule -a 'Friends List' state=floating focus=off
bspc rule -a 'Steam - News' state=floating focus=off
bspc rule -a Zathura state=tiled
bspc rule -a Gsimplecal state=floating center=on follow=on

