[colors.primary]
    background = '#252630'
    foreground = '#a0a8b7'

[colors.normal]
    black =   '#1f2329'
    red =     '#e55561'
    green =   '#8ebd6b'
    yellow =  '#e2b86b'
    blue =    '#4fa6ed'
    magenta = '#bf68d9'
    cyan =    '#48b0bd'
    white =   '#a0a8b7'

[colors.bright]
    black =   '#383d45'
    red =     '#a94650'
    green =   '#6c8e57'
    yellow =  '#a78b57'
    blue =    '#407eb2'
    magenta = '#8f53a4'
    cyan =    '#3b8590'
    white =   '#79808c'
