#!/bin/bash

BACKGROUND_COLOR="#252630"

ACCENT_COLOR="#4fa6ed"
WARNING_COLOR="#e2b86b"
ERROR_COLOR="#e55561"
SUCCESS_COLOR="#8ebd6b"

ACCENT_COLOR_NAME="blue"
WARNING_COLOR_NAME="yellow"
ERROR_COLOR_NAME="red"
SUCCESS_COLOR_NAME="green"

