#!/bin/bash

BACKGROUND_COLOR="#282828"

ACCENT_COLOR="#d8a657"
WARNING_COLOR="#d3869b"
ERROR_COLOR="#ea6962"
SUCCESS_COLOR="#a9b665"

ACCENT_COLOR_NAME="yellow"
WARNING_COLOR_NAME="magenta"
ERROR_COLOR_NAME="red"
SUCCESS_COLOR_NAME="green"

