[colors.primary]
    background = '#2d353b'
    foreground = '#d3c6aa'

[colors.normal]
    black =   '#2d353b'
    red =     '#e67e80'
    green =   '#a7c080'
    yellow =  '#dbbc7f'
    blue =    '#7fbbb3'
    magenta = '#d699b6'
    cyan =    '#83c092'
    white =   '#d3c6aa'

[colors.bright]
    black =   '#4e5251'
    red =     '#ae686b'
    green =   '#82966b'
    yellow =  '#a6936a'
    blue =    '#66928f'
    magenta = '#a37b91'
    cyan =    '#699677'
    white =   '#a19a88'
