[colors.primary]
    background = '#2e3440'
    foreground = '#d8dee9'

[colors.normal]
    black =   '#2e3440'
    red =     '#bf616a'
    green =   '#a3be8c'
    yellow =  '#ebcb8b'
    blue =    '#5e81ac'
    magenta = '#b48ead'
    cyan =    '#88c0d0'
    white =   '#d8dee9'

[colors.bright]
    black =   '#505661'
    red =     '#93535d'
    green =   '#7f9475'
    yellow =  '#b29d74'
    blue =    '#4f698b'
    magenta = '#8b728c'
    cyan =    '#6c95a4'
    white =   '#a5aab6'
