#!/bin/bash

BACKGROUND_COLOR="#2e3440"

ACCENT_COLOR="#5e81ac"
WARNING_COLOR="#ebcb8b"
ERROR_COLOR="#bf616a"
SUCCESS_COLOR="#a3be8c"

ACCENT_COLOR_NAME="blue"
WARNING_COLOR_NAME="yellow"
ERROR_COLOR_NAME="red"
SUCCESS_COLOR_NAME="green"

