#!/usr/bin/bash

readonly THEME_DIR="$1"

if ! command -v inkscape; then 
    echo "Inkscape not found"
    exit 1
fi

if [[ -z "${THEME_DIR}" ]]; then 
    echo "THEME_DIR doesn't specified"
    exit 2
fi 

readonly GTK3_ASSETS=(
    "selectionmode-checkbox-unchecked"
    "selectionmode-checkbox-checked"
    "scale-horz-marks-before-slider"
    "scale-horz-marks-before-slider-disabled"
    "scale-horz-marks-after-slider"
    "scale-horz-marks-after-slider-disabled"
    "scale-vert-marks-before-slider"
    "scale-vert-marks-before-slider-disabled"
    "scale-vert-marks-after-slider"
    "scale-vert-marks-after-slider-disabled"
    "selectionmode-checkbox-unchecked"
    "selectionmode-checkbox-checked"
    "scale-horz-marks-before-slider"
    "scale-horz-marks-before-slider-disabled"
    "scale-horz-marks-after-slider"
    "scale-horz-marks-after-slider-disabled"
    "scale-vert-marks-before-slider"
    "scale-vert-marks-before-slider-disabled"
    "scale-vert-marks-after-slider"
    "scale-vert-marks-after-slider-disabled"
)

readonly GTK2_ASSETS=(
    "entry-background-normal"
    "entry-background-disabled"
    "entry"
    "entry-hover"
    "entry-disabled"
    "flat-button"
    "flat-button-hover"
    "flat-button-active"
    "flat-button-disabled"
    "button"
    "button-hover"
    "button-active"
    "button-disabled"
    "combo-left-entry"
    "combo-left-entry-hover"
    "combo-left-entry-disabled"
    "combo-right-entry"
    "combo-right-entry-hover"
    "combo-right-entry-disabled"
    "spin-ltr-up"
    "spin-ltr-up-hover"
    "spin-ltr-up-disabled"
    "spin-ltr-down"
    "spin-ltr-down-hover"
    "spin-ltr-down-disabled"
    "spin-rtl-up"
    "spin-rtl-up-hover"
    "spin-rtl-up-disabled"
    "spin-rtl-down"
    "spin-rtl-down-hover"
    "spin-rtl-down-disabled" 
    "checkbox-unchecked"
    "checkbox-unchecked-hover"
    "checkbox-unchecked-active"
    "checkbox-unchecked-disabled"
    "radio-unchecked"
    "radio-unchecked-hover"
    "radio-unchecked-active"
    "radio-unchecked-disabled"
    "menu-checkbox-unchecked"
    "menu-checkbox-unchecked-disabled"
    "menu-radio-unchecked"
    "menu-radio-unchecked-disabled"
    "scale-slider-disabled"
    "scale-horz-trough"
    "scale-horz-trough-disabled"
    "scale-vert-trough"
    "scale-vert-trough-disabled"
    "scrollbar-horz-slider"
    "scrollbar-horz-slider-hover"
    "scrollbar-horz-slider-active"
    "scrollbar-horz-slider-disabled"
    "scrollbar-horz-trough"
    "scrollbar-vert-ltr-slider"
    "scrollbar-vert-ltr-slider-hover"
    "scrollbar-vert-ltr-slider-active"
    "scrollbar-vert-ltr-slider-disabled"
    "scrollbar-vert-ltr-trough"
    "scrollbar-vert-rtl-slider"
    "scrollbar-vert-rtl-slider-hover"
    "scrollbar-vert-rtl-slider-active"
    "scrollbar-vert-rtl-slider-disabled"
    "scrollbar-vert-rtl-trough"
    "handle-horz"
    "handle-horz-hover"
    "handle-horz-active"
    "handle-vert"
    "handle-vert-hover"
    "handle-vert-active"
    "pan-up"
    "pan-up-disabled"
    "pan-up-alt"
    "pan-up-alt-disabled"
    "pan-down"
    "pan-down-disabled"
    "pan-down-alt"
    "pan-down-alt-disabled"
    "pan-left"
    "pan-left-disabled"
    "pan-left-alt"
    "pan-left-alt-disabled"
    "pan-left-semi"
    "pan-right"
    "pan-right-disabled"
    "pan-right-alt"
    "pan-right-alt-disabled"
    "pan-right-semi"
    "border"
    "progressbar-trough"
    "frame"
    "frame-notebook"
    "frame-inline"
    "focus"
    "treeview-ltr-button"
    "treeview-ltr-button-hover"
    "treeview-ltr-button-active"
    "treeview-rtl-button"
    "treeview-rtl-button-hover"
    "treeview-rtl-button-active"
    "entry-active"
    "combo-left-entry-active"
    "combo-right-entry-active"
    "spin-ltr-up-active"
    "spin-ltr-down-active"
    "spin-rtl-up-active"
    "spin-rtl-down-active"
    "checkbox-checked"
    "checkbox-checked-hover"
    "checkbox-checked-active"
    "checkbox-checked-disabled"
    "checkbox-mixed"
    "checkbox-mixed-hover"
    "checkbox-mixed-active"
    "checkbox-mixed-disabled"
    "radio-checked"
    "radio-checked-hover"
    "radio-checked-active"
    "radio-checked-disabled"
    "radio-mixed"
    "radio-mixed-hover"
    "radio-mixed-active"
    "radio-mixed-disabled"
    "menu-checkbox-checked"
    "menu-checkbox-checked-disabled"
    "menu-checkbox-mixed"
    "menu-checkbox-mixed-disabled"
    "menu-radio-checked"
    "menu-radio-checked-disabled"
    "menu-radio-mixed"
    "menu-radio-mixed-disabled"
    "scale-slider"
    "scale-slider-hover"
    "scale-slider-active"
    "scale-horz-trough-active"
    "scale-vert-trough-active"
    "tab"
    "progressbar-progress"
)

function build_export_actions() {
    local -r OUT_DIR="$1"
    local -r DPI="$2"
    shift 2
    local -r ids=("$@")

    local actions=("export-id-only:false;export-do;")
    for id in "${ids[@]}"; do
        if [[ -n "${DPI}" ]]; then
            actions+=("export-id:${id};export-id-only:true;export-area-drawing:true;export-type:png;export-dpi:${DPI};export-filename:${OUT_DIR}/${id}@2.png;export-do;")
        else
            actions+=("export-id:${id};export-id-only:true;export-area-drawing:true;export-type:png;export-filename:${OUT_DIR}/${id}.png;export-do;")
        fi 
    done 

    printf '%s' "${actions[*]}"
}

readonly GTK3_ASSETS_DIR="${THEME_DIR}/gtk3-assets"
readonly GTK2_ASSETS_DIR="${THEME_DIR}/gtk2-assets"
readonly GTK3_SRC_FILE="${THEME_DIR}/gtk3-assets.svg"
readonly GTK2_SRC_FILE="${THEME_DIR}/gtk2-assets.svg"

[[ -d "${GTK3_ASSETS_DIR}" ]] && rm -rf "${GTK3_ASSETS_DIR}"
mkdir -p "${GTK3_ASSETS_DIR}"

inkscape --batch-process "${GTK3_SRC_FILE}" --actions="$(build_export_actions "${GTK3_ASSETS_DIR}" "" "${GTK3_ASSETS[@]}")" > /dev/null
inkscape --batch-process "${GTK3_SRC_FILE}" --actions="$(build_export_actions "${GTK3_ASSETS_DIR}" 192 "${GTK3_ASSETS[@]}")" > /dev/null

# Render GTK2 assets
[[ -d "${GTK2_ASSETS_DIR}" ]] && rm -rf "${GTK2_ASSETS_DIR}"
mkdir -p "${GTK2_ASSETS_DIR}"
inkscape --batch-process "${GTK2_SRC_FILE}" --actions="$(build_export_actions "${GTK2_ASSETS_DIR}" "" "${GTK2_ASSETS[@]}")" > /dev/null

