[global]
    frame_color = "{foreground.base}"
    background = "{background.bright}"
    foreground = "{foreground.base}"

[urgency_normal]
    foreground = "{foreground.bright}"
    frame_color = "{primary.base}"

[urgency_critical]
    foreground = "{warning.base}"
    frame_color = "{warning.base}"
