[global]
    frame_color = "{foreground.base}"
    background = "{background.bright}"
    foreground = "{foreground.base}"

[urgency_normal]
    foreground = "{foreground.bright}"
    frame_color = "{accent.base}"

[urgency_critical]
    foreground = "{error.base}"
    frame_color = "{error.base}"
