background {background.base}
foreground {foreground.base}

color0 {black}
color8 {black.bright}

color1 {red}
color9 {red.bright}

color2 {green}
color10 {green.bright}

color3 {yellow}
color11 {yellow.bright}

color4 {blue}
color12 {blue.bright}

color5 {magenta}
color13 {magenta.bright}

color6 {cyan}
color14 {cyan.bright}

color7 {white}
color15 {white.bright}
