local M = {{
    none = "NONE",
    background_base = "{background.base}",
    background_bright = "{background.bright}",
    background_brightest = "{background.brightest}",
    background_dim = "{background.dim}",

    foreground_base = "{foreground.base}",
    foreground_bright = "{foreground.bright}",
    foreground_dim = "{foreground.dim}",

    black = "{black}",
    red = "{red}",
    green = "{green}",
    blue = "{blue}",
    yellow = "{yellow}",
    cyan = "{cyan}",
    magenta = "{magenta}",
    white = "{white}",

    orange = "{orange}",
    yellowgreen = "{yellowgreen}",
    cyangreen = "{cyangreen}",
    azure = "{azure}",
    violet = "{violet}",
    rose = "{rose}",

    black_bright = "{black.bright}",
    red_bright = "{red.bright}",
    green_bright = "{green.bright}",
    blue_bright = "{blue.bright}",
    yellow_bright = "{yellow.bright}",
    cyan_bright = "{cyan.bright}",
    magenta_bright = "{magenta.bright}",
    white_bright = "{white.bright}",

    primary_base = "{primary.base}",
    primary_bright = "{primary.bright}",
    primary_dim = "{primary.dim}",
    primary_background = "{primary.background}",
    primary_foreground = "{primary.foreground}",
    secondary_base = "{secondary.base}",
    secondary_bright = "{secondary.bright}",
    secondary_dim = "{secondary.dim}",
    secondary_background = "{secondary.background}",
    secondary_foreground = "{secondary.foreground}",
    warning_base = "{warning.base}",
    warning_bright = "{warning.bright}",
    warning_dim = "{warning.dim}",
    warning_background = "{warning.background}",
    warning_foreground = "{warning.foreground}",
}}

return M
