color background            white               black
color listnormal            white               black
color listfocus             black               {accent.name}       bold
color listnormal_unread     white               black               bold
color listfocus_unread      black               {accent.name}       bold
color title                 {accent.name}	        black               bold
color info                  {accent.name}         black               bold

color hint-key              {accent.name}       black               bold
color hint-separator        white               black               bold
color hint-keys-delimiter   black               black
color hint-description      white               black 
color article               white               black

highlight article "^(Feed|Link):"            {accent.name}         default     bold
highlight article "^(Title|Date|Author):"    {accent.name}         default     bold
highlight article "https?://[^ ]+"              {accent.name}         default     underline
highlight article "\\[image\\ [0-9]+\\]"        {accent.name}         default     bold
highlight feedlist "^─.*$"                      {accent.name}       black       bold
