color background            white               black
color listnormal            white               black
color listfocus             black               {primary.name}      bold
color listnormal_unread     white               black               bold
color listfocus_unread      black               {primary.name}      bold
color title                 {secondary.name}	black               bold
color info                  {secondary.name}    black               bold

color hint-key              {primary.name}      black               bold
color hint-separator        white               black               bold
color hint-keys-delimiter   black               black
color hint-description      white               black 
color article               white               black

highlight article "^(Feed|Link):.*$"            {warning.name}      default     bold
highlight article "^(Title|Date|Author):.*$"    {primary.name}      default     bold
highlight article "https?://[^ ]+"              {warning.name}      default     underline
highlight article "\\[image\\ [0-9]+\\]"        {secondary.name}    default     bold
highlight feedlist "^─.*$"                      {primary.name}      black       bold
