BACKGROUND_COLOR="{background.base}"
BACKGROUND_BRIGHT_COLOR="{background.bright}"
ACCENT_COLOR="{accent.base}"
INFO_COLOR="{info.base}"
SUCCESS_COLOR="{success.base}"
WARNING_COLOR="{warning.base}"
ERROR_COLOR="{error.base}"

ACCENT_COLOR_NAME="{accent.name}"
INFO_COLOR_NAME="{info.name}"
SUCCESS_COLOR_NAME="{success.name}"
WARNING_COLOR_NAME="{warning.name}"
ERROR_COLOR_NAME="{error.name}"

ACCENT_COLOR_ANSI="{accent.ansi}"
INFO_COLOR_ANSI="{info.ansi}"
SUCCESS_COLOR_ANSI="{success.ansi}"
WARNING_COLOR_ANSI="{warning.ansi}"
ERROR_COLOR_ANSI="{error.ansi}"
