"$schema" = 'https://starship.rs/config-schema.json'

format = """
$hostname\
$username\
$directory\
$git_branch\
$git_commit\
${{custom.git_status_short}}\
$character"""

add_newline = true 
palette = "generic"

[palettes.generic]
primary = "{primary}"
secondary = "{secondary}"
warning = "{warning}"

[hostname]
ssh_symbol = ""
style = "warning"
format = "[$ssh_symbol$hostname » ]($style)"

[username]
style_user = "primary"
style_root = "warning"
format = "[$user » ]($style)"

[directory]
style = "primary"
read_only = "󰉐 "
format = "[$read_only]($read_only_style)[$path]($style)"

[git_branch]
symbol = " "
style = "secondary"
format = "[ » $symbol$branch(:$remote_branch)]($style)"

[git_commit]
style = "secondary"
tag_disabled = false
tag_symbol = "󰓹 "
format = '[ $tag]($style)[\($hash\)](italic secondary)'

[custom.git_status_short]
command = '[ "$(git status --short 2>/dev/null)" ] && echo "(~)"'
require_repo = true
when = true
description = "Short indication for 'git status' (is any changes in the repo)"
style = "warning"
format = "[ ($output)]($style)"

[character]
success_symbol = "[ »](bold primary)" 
error_symbol = "[ !»](bold warning)"
vimcmd_symbol = "[ ](bold warning)"


