set -g @background_bright "{background.bright}"
set -g @foreground_base "{foreground.base}"
set -g @foreground_dim "{foreground.dim}"
set -g @primary_base "{primary.base}"
set -g @primary_background "{primary.background}"
