set -g @background_bright "{background.bright}"
set -g @foreground_base "{foreground.base}"
set -g @foreground_dim "{foreground.dim}"
set -g @accent "{accent.base}"
set -g @accent_contrast "{accent.background}"
