[mgr]
cwd = {{ fg = "{accent.base}" }}

hovered         = {{ reversed = true }}
preview_hovered = {{ underline = true }}

find_keyword  = {{ fg = "red", bold = true, italic = true, underline = true }}
find_position = {{ bg = "reset", bold = true, italic = true }}

marker_copied   = {{ fg = "{success.base}", bg = "{success.base}" }}
marker_cut      = {{ fg = "{warning.base}", bg = "{warning.base}" }}
marker_marked   = {{ fg = "{accent.base}",  bg = "{accent.base}" }}
marker_selected = {{ fg = "{accent.base}", bg = "{accent.base}" }}

tab_active   = {{ reversed = true }}
tab_inactive = {{}}
tab_width    = 1

count_copied   = {{ fg = "{foreground.base}", bg = "green" }}
count_cut      = {{ fg = "{foreground.base}", bg = "red" }}
count_selected = {{ fg = "{foreground.base}", bg = "yellow" }}

border_symbol = "│"
border_style  = {{ fg = "{foreground.dim}" }}

[status]
sep_left = {{ open = "", close = "»" }}
sep_right = {{ open = "«", close = "" }}

[mode]
normal_main = {{ fg = "{accent.base}", bg = "reset", bold = true }}
normal_alt  = {{ fg = "{accent.base}", bg = "reset" }}
select_main = {{ fg = "red", bg = "reset", bold = true }}
select_alt  = {{ fg = "red", bg = "reset" }}
unset_main = {{ fg = "red", bg = "reset", bold = true }}
unset_alt  = {{ fg = "red", bg = "reset" }}

perm_sep   = {{ fg = "darkgray" }}
perm_type  = {{ fg = "green" }}
perm_read  = {{ fg = "yellow" }}
perm_write = {{ fg = "red" }}
perm_exec  = {{ fg = "cyan" }}

progress_label  = {{ bold = true }}
progress_normal = {{ fg = "{accent.base}", bg = "{background.base}" }}
progress_error  = {{ fg = "{error.base}", bg = "{background.base}" }}

[which]
cols            = 3
mask            = {{ bg = "{background.base}" }}
cand            = {{ fg = "lightcyan" }}
rest            = {{ fg = "darkgray" }}
desc            = {{ fg = "lightmagenta" }}
separator       = "  "
separator_style = {{ fg = "darkgray" }}

[confirm]
border     = {{ fg = "{accent.base}" }}
title      = {{ fg = "{accent.base}" }}
content    = {{}}
list       = {{}}
btn_yes    = {{ reversed = true }}
btn_no     = {{}}
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

[spot]
border = {{ fg = "{accent.base}" }}
title  = {{ fg = "{accent.base}" }}

[notify]
title_info  = {{ fg = "{info.base}" }}
title_warn  = {{ fg = "{warning.base}" }}
title_error = {{ fg = "{error.base}" }}

[pick]
border   = {{ fg = "{accent.base}" }}
active   = {{ fg = "magenta", bold = true }}
inactive = {{}}

[input]
border   = {{ fg = "{accent.base}" }}
title    = {{}}
value    = {{}}
selected = {{ reversed = true }}

[completion]
border   = {{ fg = "{accent.base}" }}
active   = {{ reversed = true }}
inactive = {{}}

[tasks]
border  = {{ fg = "{accent.base}" }}
title   = {{}}
hovered = {{ fg = "magenta", underline = true }}

[tabs]
active = {{ fg = "{accent.background}", bg = "{accent.base}" }}
inactive = {{ fg = "{foreground.base}", bg = "{background.bright}" }}
sep_inner = {{ open = "", close = "" }}
sep_outer = {{ open = "", close = "" }}

[help]
on      = {{ fg = "{accent.base}", bold = true }}
run     = {{ fg = "{accent.base}", italic = true }}
desc    = {{}}
hovered = {{ reversed = true }}
footer  = {{ fg = "{background.base}", bg = "{foreground.base}" }}

[filetype]
rules = [
	# Special files
	{{ url = "*", fg = "{foreground.base}" }},
    {{ url = "*", is = "link", italic = true }},
	{{ url = "*", is = "orphan", bg = "{error.base}" }},
	{{ url = "*", is = "exec"  , fg = "{error.base}" }},
	{{ url = "*/", fg = "{accent.base}" }}
]
